[package]
name = "deli-audio"
version = "0.1.0"
edition = "2024"

[dependencies]
libpulse-binding = "2.28"
libpulse-simple-binding = "2.28"
log = "0.4"
tokio = { version = "1", features = ["rt", "sync"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "sync", "macros"] }
